name: feed_me
description: chat gpt test

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  chat_gpt_sdk: ^2.0.7
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  flutter_secure_storage: ^8.0.0
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  get: ^4.6.5
  get_it: ^7.2.0
  google_fonts: ^4.0.3
  http: ^0.13.5
  lottie: ^2.3.1
  sizer: ^2.0.15
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_launcher_icons: "^0.13.0"
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo.png
    - assets/lottie/
